### ISSUE TITLE
Any chance for Pro Version

### ISSUE THREAD

**Issue by simplyaakif** [afatmustafa/blade-hugeicons#3]
Just wondering when will this package allow for pro version?

**Comment by afatmustafa** [comment]
Hi, I don't think this is possible without writing custom code, because Hugeicons is normally an NPM package, it doesn't have the level of svg list that Bladeicons wants, so even getting the free icons from the NPM package required writing custom code.

If Hugeicons pro provided the svgs of the icons in a folder, we could do this, but I don't think it will happen as it is now. If you have a pro membership, I can write a special package if you can contact me via my e-mail.

**Comment by simplyaakif** [comment]
Thanks for promptly replying. Yes I have pro access. I will use the blade icons package route and load from folder.

Just wanted to see if there was something originally planned by you.

**Comment by afatmustafa** [comment]
You are welcome, I think it is not possible to do it as a public package.
